name: Release Bot

on:
  push:
    branches:
      - master
      - dev

jobs:
  Windows-x64:
    runs-on: windows-latest

    steps:
      - name: Checkout Era.js
        uses: actions/checkout@v2
        with:
          repository: miswanting/Era.js
          path: Era.js

      - name: Checkout Era.js-SDK
        uses: actions/checkout@v2
        with:
          path: Era.js-SDK

      - name: Setup Node.js Enviroment
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
          check-latest: true

      - name: Setup Python 3 Enviroment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Setup Front-End Enviroment
        run: |
          cd Era.js\Next\FrontEnd
          npm run setup
          npx electron-builder --dir

      - name: Assemble SDK
        run: |
          mkdir Era.js-SDK\erajs
          xcopy Era.js\Next\BackEnd\erajs Era.js-SDK\erajs\ /E
          Remove-Item Era.js-SDK\prebuilt\*
          xcopy Era.js\Next\FrontEnd\dist\win-unpacked\ Era.js-SDK\prebuilt\ /E
          Compress-Archive -Path Era.js-SDK\* -DestinationPath Era.js-SDK-${{ github.ref }}.zip -CompressionLevel Optimal

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Era.js-SDK-${{ github.ref }}.zip
          asset_name: Era.js-SDK-${{ github.ref }}.zip
          asset_content_type: application/zip

  Windows-x86:
    runs-on: windows-latest

    steps:
      - name: Checkout Era.js
        uses: actions/checkout@v2
        with:
          repository: miswanting/Era.js
          path: Era.js

      - name: Checkout Era.js-SDK
        uses: actions/checkout@v2
        with:
          path: Era.js-SDK

      - name: Setup Node.js Enviroment
        run: dir

      - name: Setup Python 3 Enviroment
        run: dir
  # Release Linux x64:
  # Release Linux x32:
