name: Release Bot

on:
  push:
    branches:
      - master
      - dev

jobs:
  Windows-x64:
    runs-on: windows-latest

    steps:
      - name: Checkout Era.js
        uses: actions/checkout@v2
        with:
          repository: miswanting/Era.js
          path: Era.js

      - name: Checkout Era.js-SDK
        uses: actions/checkout@v2
        with:
          path: Era.js-SDK

      - name: Setup Node.js Enviroment
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
          check-latest: true

      - name: Setup Python 3 Enviroment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Setup Front-End Enviroment
        run: |
          cd Era.js\Next\FrontEnd
          npm run setup

      - name: Setup Back-End Enviroment
        run: |
          dir

  Windows-x86:
    runs-on: windows-latest

    steps:
      - name: Checkout Era.js
        uses: actions/checkout@v2
        with:
          repository: miswanting/Era.js
          path: Era.js

      - name: Checkout Era.js-SDK
        uses: actions/checkout@v2
        with:
          path: Era.js-SDK

      - name: Setup Node.js Enviroment
        run: dir

      - name: Setup Python 3 Enviroment
        run: dir
  # Release Linux x64:
  # Release Linux x32:
